# Site configuration
title = "sergiorivera.dev"
description = "A simple blog built with a minimal static site generator"
base_url = "https://sergiorivera.dev"
language = "en"

# Author information
[author]
name = "Sergio Rivera"

# Site customization
[params]
# Main settings
posts_per_page = 10
show_reading_time = true
date_format = "%B %d, %Y"
